// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorApp1.Models;

public partial class EmpTable
{
    public string Name { get; set; }

    public string Dob { get; set; }

    public string Location { get; set; }

    public string Designation { get; set; }

    public string EmailAddress { get; set; }

    public bool? Deleted { get; set; }

    public int Id { get; set; }

    public string Gender { get; set; }

    public virtual ICollection<SkillsTable> Skills { get; set; } = new List<SkillsTable>();
}