// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace BlazorApp1.Models
{
    public partial class GetSkilsResult
    {
        public int Id { get; set; }
        public string Skills { get; set; }
    }
}
