// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorApp1.Models;

public partial class SkillsTable
{
    public int Id { get; set; }

    public string Skills { get; set; }

    public virtual ICollection<EmpTable> Employees { get; set; } = new List<EmpTable>();
}